### ISSUE TITLE
Wrong warning sign emoji?

### ISSUE THREAD

**Issue by ghost** [gary149/rocket-emoji#2]
Currently a black-and-white warning sign emoji comes up in Rocket Emoji.

…Instead of the regular color one on this page: https://emojipedia.org/emoji/%E2%9A%A0/

Can you please fix this?…

Thank you so much.

**Comment by gary149** [comment]
What Operating system are you on ? It's seems there is no colored warning emoji on macos.
![image](https://user-images.githubusercontent.com/3841370/83394278-9974b180-a3f8-11ea-8154-f5493c2433b3.png)

**Comment by ghost** [comment]
I am on macOS, yes.

But if I copy the emoji from the Character row on that page (https://emojipedia.org/emoji/%E2%9A%A0/) instead of on Rocket Emoji, I get the colored version… — I can see it in my clipboard manager (CopyLess 2), and when I paste it to Sublime Text.

So there seem to be two versions of the emoji somehow on macOS.

…If, instead, I copy the Rocket Emoji one I get the black-and-white one… both on the clipboard manager and on Sublime Text.

**Comment by gary149** [comment]
> …If, instead, I copy the Rocket Emoji one I get the black-and-white one… both on the clipboard manager and on Sublime Text.  

e324620c6a31255a620fddf4e00b81222040790d It should work now 😅 .

**Comment by ghost** [comment]
The copying & pasting does work now! Thank you. 🙂

Not very important, but the black-and-white version of the emoji still shows up in the Rocket Emoji list… — Any chance that the colored version could show up instead?

BTW, thanks for Rocket Emoji! I use it as my main emoji picker when I'm writing. ☀️
